//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int ID { get; set; }
        public int PerID { get; set; }
        public int FormID { get; set; }
        public bool C_Access { get; set; }
        public bool C_Insert { get; set; }
        public bool C_Delete { get; set; }
        public bool C_Update { get; set; }
        public bool C_Print { get; set; }
        public bool C_Import { get; set; }
        public bool C_Export { get; set; }
    }
}
