//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public float GiaTien { get; set; }
        public int SoLuong { get; set; }
        public string DonViTinh { get; set; }
        public string NSX { get; set; }
    }
}
